name: "Run Bash Script with Inputs"
description: "A custom action to run a bash script with inputs"
inputs:
  name:
    description: "Name of the user"
    required: true
  greeting:
    description: "Greeting message"
    required: false
    default: "Hello"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run bash script
      run: ./main.sh "${{ inputs.name }}" "${{ inputs.greeting }}"
      shell: bash
