name: Job-to-Job Communication(push test)

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-output.outputs.result }}
    steps:
      - name: "Step 1: Generate a value"
        run: echo "GeneratedValue" > value.txt

      - name: "Step 2: Set the value to GITHUB_OUTPUT"
        id: set-output
        run: echo "result=$(cat value.txt)" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: "Step 1: Use the value from job1"
        run: 'echo "Received value from job1: ${{ needs.job1.outputs.result }}"'
