name: "Run Bash Script Example"
on:
  push:
    branches:
      - main

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run custom action
        uses: ./
        with:
          name: "Tom"
          greeting: "こんにちは"
